Repository Mikael-Asaas/Asaas, pull requests merged in 2022-05, with the labels that each got.

#8 Branch mvc payer list/show
  grails-app/assets/javascripts/index.js
  grails-app/assets/javascripts/index/controller.js
  grails-app/assets/javascripts/index/fillFormPostalCode.js
  grails-app/assets/javascripts/payer.js
  grails-app/assets/javascripts/payer/save.js
  grails-app/assets/javascripts/payer/show.js
  grails-app/assets/javascripts/utils/fillFormPostalCode.js
  grails-app/assets/javascripts/utils/mask.form.js
  grails-app/assets/javascripts/utils/mask.lib.js
  grails-app/assets/javascripts/utils/searchPostalCode.js
  grails-app/assets/stylesheets/main.css
  grails-app/controllers/com/desafio/domain/PayerController.groovy
  grails-app/domain/com/desafio/domain/Payer.groovy
  grails-app/i18n/messages.properties
  grails-app/services/com/desafio/domain/PayerService.groovy
  grails-app/views/index.gsp
  grails-app/views/payer/_list.gsp
  grails-app/views/payer/create.gsp
  grails-app/views/payer/index.gsp
  grails-app/views/payer/show.gsp
  src/main/groovy/com/desafio/BaseController.groovy
Labels: Aguardando PR, Approved

#7 Branch mvc refatorando customer
  grails-app/assets/javascripts/customer.js
  grails-app/assets/javascripts/customer/save.js
  grails-app/assets/javascripts/customer/show.js
  grails-app/assets/javascripts/index/IndexController.js
  grails-app/assets/javascripts/utils/fillFormPostalCode.js
  grails-app/assets/javascripts/utils/mask.form.js
  grails-app/assets/javascripts/utils/mask.lib.js
  grails-app/assets/stylesheets/main.css
  grails-app/controllers/com/desafio/domain/CustomerController.groovy
  grails-app/domain/com/desafio/domain/Customer.groovy
  grails-app/services/com/desafio/domain/CustomerService.groovy
  grails-app/views/customer/_list.gsp
  grails-app/views/customer/create.gsp
  grails-app/views/customer/edit.gsp
  grails-app/views/customer/index.gsp
  grails-app/views/customer/show.gsp
  grails-app/views/index.gsp
  src/main/groovy/com/desafio/BaseController.groovy
Labels: Approved

#9 Relacionando um customer a um payer
  grails-app/controllers/com/desafio/domain/CustomerController.groovy
  grails-app/controllers/com/desafio/domain/PayerController.groovy
  grails-app/domain/com/desafio/domain/Customer.groovy
  grails-app/domain/com/desafio/domain/customer/Customer.groovy
  grails-app/domain/com/desafio/domain/payer/Payer.groovy
  grails-app/services/com/desafio/domain/CustomerService.groovy
  grails-app/services/com/desafio/domain/customer/CustomerService.groovy
  grails-app/services/com/desafio/domain/payer/PayerService.groovy
  grails-app/views/customer/_list.gsp
  grails-app/views/customer/create.gsp
  grails-app/views/customer/edit.gsp
  grails-app/views/customer/index.gsp
  grails-app/views/customer/show.gsp
  grails-app/views/payer/create.gsp
  grails-app/views/payer/show.gsp
Labels: Aguardando PR

#11 Estrutura Payment: Criando Domain, Enums e BaseEntity
  grails-app/domain/com/desafio/domain/payment/Payment.groovy
  grails-app/i18n/messages.properties
  src/main/groovy/com/desafio/base/BaseController.groovy
  src/main/groovy/com/desafio/base/BaseEntity.groovy
  src/main/groovy/com/desafio/enums/PaymentMethod.groovy
  src/main/groovy/com/desafio/enums/PaymentStatus.groovy
Labels: Aguardando PR, Approved
